/*
  ===========================================================
  SITE CONFIG — edit everything here. No HTML/CSS knowledge needed.
  ===========================================================
  This is the ONLY file you need to touch to customize the content
  of the site. Save your changes and refresh the page (or push to
  GitHub) to see them live.

  (Generated by admin.html — it's still just a plain JavaScript file,
  so you can keep editing it by hand too.)
*/

const CONFIG = {

  // ---------- Site-wide ----------
  site: {
    title: "Sravani Saha",
    description: "Writer, artist, and founder of a mindfulness circle.",
    // Path to a favicon image (optional). Leave as "" to skip.
    favicon: ""
  },

  // ---------- Admin access ----------
  // Password protection for admin.html. This is a static site with no
  // server, so this is a basic deterrent against casual visitors, not
  // real security — the hash below is public in this file, and anyone
  // determined could brute-force it offline. Don't reuse a sensitive
  // password here.
  //
  // Change your password from the Security section in admin.html, then
  // download/copy config.js and redeploy.
  admin: {
    passwordHash: "2112a2ec3bd3cfe9c324d361464a838cea5ad5560aada8752cc040916aace32d"
  },

  // ---------- About / Hero ----------
  person: {
    name: "Sravani Saha",
    tagline: "Writer. Artist. Guide.",
    bio: "Welcome — I write, I make things by hand, and I hold space for a small mindfulness circle. This is where all of it lives.",
    // Path to a profile photo. Put your image in the /images folder
    // and reference it like "images/profile.jpg". Leave "" for a
    // placeholder initial instead of a photo.
    avatar: "",
    // Shown in the footer as "Contact me at ...", right above the
    // social icons. Click-to-copy, not a mailto link.
    email: "s.sravani@gmail.com"
  },

  // ---------- Socials ----------
  // "icon" can be any of: instagram, twitter, linkedin, github, email,
  // youtube, tiktok, facebook, pinterest, substack, medium, or "link" (generic).
  socials: [
    { name: "Instagram", icon: "instagram", url: "https://www.instagram.com/artviolet_sravani/" },
    { name: "Substack", icon: "substack", url: "https://substack.com/@sravanisaha" },
    { name: "Medium", icon: "medium", url: "https://medium.com/@sravss" },
    { name: "LinkedIn", icon: "linkedin", url: "https://in.linkedin.com/in/sravanisaha" }
  ],

  // ---------- Section links ----------
  // Where the "View all →" links on the homepage's Writing and Art
  // sections point to. Default to this site's own writing.html/art.html
  // pages, but you can point either one anywhere else instead — e.g. an
  // external blog or shop — and it'll open in a new tab automatically.
  links: {
    writingViewAll: "writing.html",
    artViewAll: "art.html"
  },

  // ---------- Writing ----------
  // Shown as a preview (first 3) on the home page, and in full on writing.html.
  // "url" can be an external link (e.g. Substack post, Medium, PDF) or
  // a local file path. "external" set to true opens it in a new tab.
  writing: [
    {
      title: "On Stillness and Starting Over",
      date: "2026-06-01",
      excerpt: "A short essay on what it means to begin again, quietly.",
      url: "#",
      external: true
    },
    {
      title: "Notes from a Slow Morning",
      date: "2026-04-12",
      excerpt: "Reflections on routine, attention, and the ordinary.",
      url: "#",
      external: true
    },
    {
      title: "Letters I Never Sent",
      date: "2026-02-20",
      excerpt: "A collection of short pieces written and rewritten.",
      url: "#",
      external: true
    }
  ],

  // ---------- Art ----------
  // "image" should point to a file in /images (e.g. "images/art1.jpg").
  // "buyUrl" can link to Etsy, Gumroad, Ko-fi, Shopify, or anywhere you
  // sell. Set "sold" to true to show a "Sold" badge instead of a Buy button.
  art: [
    {
      title: "Quiet Morning",
      image: "",
      price: "$120",
      description: "Watercolor on paper, 9x12in.",
      buyUrl: "https://www.etsy.com/your-shop/listing/example",
      sold: false
    },
    {
      title: "Held",
      image: "",
      price: "$85",
      description: "Ink and gouache, 8x10in.",
      buyUrl: "https://www.etsy.com/your-shop/listing/example2",
      sold: false
    },
    {
      title: "Returning",
      image: "",
      price: "$150",
      description: "Mixed media, 11x14in.",
      buyUrl: "",
      sold: true
    }
  ],

  // ---------- Mindfulness Circle ----------
  mindfulness: {
    title: "The Quiet Circle",
    image: "",
    description: "A small, slow-paced mindfulness circle meeting weekly to sit, breathe, and share in community. No experience necessary — just a willingness to be present.",
    details: [
      "Weekly virtual sessions, 45 minutes",
      "Guided breathing and gentle reflection",
      "Small group, limited to 12 people"
    ],
    url: "https://www.yourhumanness.com/mindfulness-circle"
  }

};
